# Unit in [um]
Pad:
  layer: 10
  width: 250
  #height: 400
  height: 3500
  gap: 20 # gap between two capacitance pads

JJ:
  finger:
    layer: 10
    up:
      length: 10.0
      width: 0.2
    down:
      length: 10.0
      width: 0.3
  pad_box:
    width: 2.0
    length: 10
    gap: 4.0
  bridge:
    width: 0.9
  taper:
    width1: 10
    width2: 40
    length: 100
    gap: 10

DicingMarker:
  layer: 2
  width: 100
  # length: 400
  length: 1600

Chip: #chipのsize
  size:
    x: 3000
    y: 8000

Grid:
  bridge_width: #ここの行数...列の繰り返し回数
     - [0.9,0.85, 0.8, 0.75, 0.7,0.65,0.6,0.55,0.50,0.45, 0.9,0.85, 0.8, 0.75, 0.7,0.65,0.6,0.55,0.50,0.45]
    #- [0.9,0.85, 0.8, 0.75, 0.7,0.65,0.6,0.55,0.50,0.45]
    # - [0.7, 0.8, 0.9, 1.0, 1.1]  
    # - [0.5, 0.6, 0.7, 0.8, 0.9]
    # - [0.5, 0.6, 0.7, 0.8, 0.9]
  finger_width: #ここの行数...行の繰り返し回数
    - [0.15,0.2, 0.25, 0.3]
    - [0.15,0.2, 0.25, 0.3]
  pad_height: #ここの行数...行の繰り返し回数
      - [200,400, 1000, 2000]
      - [200,400, 1000, 2000]
  gap:
    x: 0 #1
    y: 0 #1

Chip_small:
  size:
    x: 3000
    y: 8000

Grid_small:
  bridge_width: #ここの行数...
    - [0.9,0.85, 0.8, 0.75, 0.7,0.65,0.6,0.55,0.50,0.45, 0.9,0.85, 0.8, 0.75, 0.7,0.65,0.6,0.55,0.50,0.45]
    # - [0.7, 0.8, 0.9, 1.0, 1.1]  
    # - [0.5, 0.6, 0.7, 0.8, 0.9]
    # - [0.5, 0.6, 0.7, 0.8, 0.9]
  finger_width:
    - [0.2, 0.25, 0.3]
    - [0.2, 0.25, 0.3]
    - [0.2, 0.25, 0.3]
    - [0.2, 0.25, 0.3]

  gap:
    x: 0
    y: 0

EBMarker:
  layer: 3
  pos: 
    #- [     0,      0]
    - [     0,  38400]
    #- [-19200, -28800]
    - [ 38400,      0]
    - [     0, -38400]
    #- [-19200, -38400]
    - [-38400,      0]