# Unit in [um]
Pad:
  layer: 1
  width: 250
  height: 400
  rounding: 20
  gap: 20 # gap between two capacitance pads

JJ:
  rounding: 0 # 0.05
  finger:
    layer: 1
    up:
      length: 10.0
      width: 0.2
    down:
      length: 10.0
      width: 0.3
    rounding: 0
  pad_box:
    width: 2.0
    length: 10
    gap: 4.0
  bridge:
    width: 0.9
  taper:
    width1: 10
    width2: 40
    length: 100
    gap: 10

Pad_JJ:
  rounding: 0

DicingMarker:
  layer: 1
  width: 100
  # length: 400
  length: 1600

Chip:
  size:
    x: 2000
    y: 2000

Grid:
  finger_width: 
    - [0.10, 0.12, 0.14, 0.16, 0.18, 0.20, 0.25, 0.3]
    - [0.10, 0.12, 0.14, 0.16, 0.18, 0.20, 0.25, 0.3]
  finger_height:
    - [0.3, 0.3, 0.3, 0.3]
    - [0.3, 0.3, 0.3, 0.3]  
  gap:
    x: 2
    y: 2

Text:
  string: 'str(width)'
  layer: 1 #2
  size: 40
  pos:
    x: -0.75
    y: -0.7


TestPoint:
  layer: 1 #4
  box:
    rounding: 0
    width: 50
    length: 50
  gap: 20
  pos:
    x: -0.75
    y: -0.85